import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Open_Sans({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Font-Demo",
  description: "Generated by JP",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth antialiased"
      suppressHydrationWarning
    >
      <body className={`flex min-h-screen flex-col ${inter.className}`}>
        {/* Background layer with full size and fixed position */}
        <div className="absolute top-0 left-0 w-full h-full z-[-1] bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]"></div>

        <ThemeProvider
          enableSystem
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          <main className="grow">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
